name: 機能追加(Feature request)
description: File a feature request
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        機能追加の提案に感謝します。
        
  - type: textarea
    id: feature-summary
    attributes:
      label: "🚀機能概要"
      description: 追加したい機能について教えてください
      placeholder: Tell us what you want!
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        以下、オプションです。よろしければご記入ください。

  - type: textarea
    id: reason
    attributes:
      label: "🚀なぜこの機能が必要なのか"
      description: この機能が必要な理由を教えてください
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: "🚀実装案"
      description: あなたが考える機能の実装方法を教えてください
    validations:
      required: false

  - type: textarea
    id: other
    attributes:
      label: "🚀その他(other)"
      description: その他、機能追加に関する情報があれば教えてください
    validations:
      required: false